### PR TITLE
Update package.js

### PR DESCRIPTION
**Pull request by mryraghi**

### CODE REVIEW

**Comment by fermuch** [comment]
Great. Thanks! :beers:

**Comment by fermuch** [comment]
Hello. You deleted your branch before I could merge it. If you re-create that branch, I will merge this branch, so you can stay in the history logs :)

**Comment by mryraghi** [comment]
Sorry, it was a mistake! Anyway, may I ask you how could I use your package with Imgix tokens? I've noticed that in the changelog of imgix.js they say that they prefer not to handle tokens in the client side and therefore is better to use Imgix for node.js. Since I'm using Meteor, do you know what should I do?

**Comment by fermuch** [comment]
I'm using just the basics of imgix, and currently I'm not using the "secure urls". Can you point me how you use it?

**Pull request closed without merging**
